# Build all SS3 binaries, for testing and distribution.
name: call-build-ss3
on: 
  push:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/build-ss3.yml@older-mac-compile
