# run models without estimation again
name: call-run-ss3-with-est
on: 
  push:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/run-ss3-with-est.yml@admb-dev
