name: ubuntu-64bit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: admb-project/admb
        ref: admb-13.0
    - name: flex
      run: sudo apt-get install flex
    - name: clean
      run: make clean
    - name: build
      run: |
        make
